#!/bin/sh
weight=$1
height=$2 # height를 m 단위로 변환
height_m=$(echo "scale=2; $height/100" | bc) # BMI 계산 후 10배 함
bmi=$(echo "scale=0; 10 * $weight / ($height_m * $height_m)" | bc)
if [ $bmi -ge 230 ]; then
  echo "과체중입니다."
elif [ $bmi -lt 185 ]; then
  echo "저체중입니다."
else
  echo "정상체중입니다."
fi                                                                                                                      

exit 0 
